version: '3'

services:
  app:
      build: .
      ports:
        - "8000:8000"
      depends_on:
        postgres:
          condition: service_healthy
      networks:
      - app_network    
      environment:
        - SQLALCHEMY_DATABASE_URL=postgresql+psycopg2://postgres:567234@postgres:5432/hw02

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: hw02
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network  

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge      